export const PREDEFINED_ITEMS = [
  "LED TV",
  "Fan",
  "Cooler",
  "Washing Machine",
  "Toaster",
  "Speaker",
  "Voltage Stabilizer",
  "Mixer",
  "Electric Kettle",
  "Iron",
  "Induction Cooktop",
  "Ceiling Fan",
  "Table Fan",
  "Exhaust Fan",
  "Geyser",
  "Room Heater",
  "Refrigerator (Single Door)",
  "Water Purifier (RO)",
  "Mobile Charger",
  "Extension Board",
  "Tube Light",
  "Inverter Battery",
  "Electric Wire (Bundle)",
  "Switch Board",
  "MCB",
  "Bulb (LED/Normal)",
  "Emergency Light",
  "Electric Bell",
  "Set Top Box",
  "Remote Control",
  "Digital Clock",
  "Hand Blender",
  "Chimney (Basic Model)",
];

export const GSTIN_REGEX =
  /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;
